server:
  port: 8081

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_restaurant
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true